name: fgislamic_prayer
description: A beautiful Islamic prayer app with accurate prayer times, Qibla direction, and donation features.
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.2
  flutter_compass: ^0.8.0
  audioplayers: ^5.2.1
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
    - assets/qr/
  
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700